# Workflows CI config file
# This workflow runs everyday, checks for updates of designated packages.
# Build workflow will be triggered if there's any commit pushed to this branch.
name: Check for latest releases nightly
on:
  workflow_dispatch:
  schedule:
  - cron: '30 0 * * *'

permissions:
  contents: write
  repository-projects: write

jobs:
  check-for-nightly-updates:
    runs-on:
      - self-hosted
      - aosc
      - checker
    env:
      NIGHTLY: 1
    steps:
      # Fetch abbs and workflows-ci repository
      # Checks out ABBS tree to $GITHUB_WORKSPACE/abbs
      - uses: actions/checkout@v3
        with:
          ref: 'bleeding-edge-nightly'
          fetch-depth: '0'
          token: '${{ secrets.CIP_PAT }}'
          path: 'nightly'
      # Checks out the CI scripts repository to $GITHUB_WORKSPACE/workflows-ci
      - uses: actions/checkout@v3
        with:
          repository: 'AOSC-CIP-Pilot/workflows-ci'
          ref: 'cip'
          path: 'workflows-ci'
      
      # Check for updates
      - name: 'Check for updates'
        run: |
          pushd ${{ github.workspace }}/workflows-ci
          env TREEDIR=${{ github.workspace }}/nightly NIGHTLY=${{ env.NIGHTLY }} ./check-update-job
          popd

      - name: 'Push the commits'
        run: |
          pushd ${{ github.workspace }}/nightly
          git push --force
  check-for-updates:
    runs-on:
      - self-hosted
      - aosc
      - checker
    env:
      NIGHTLY: 0
    steps:
      # Fetch abbs and workflows-ci repository
      # Checks out ABBS tree to $GITHUB_WORKSPACE/abbs
      - uses: actions/checkout@v3
        with:
          ref: 'bleeding-edge'
          fetch-depth: '0'
          token: '${{ secrets.CIP_PAT }}'
          path: 'abbs'
      # Checks out the CI scripts repository to $GITHUB_WORKSPACE/workflows-ci
      - uses: actions/checkout@v3
        with:
          repository: 'AOSC-CIP-Pilot/workflows-ci'
          ref: 'cip'
          path: 'workflows-ci'
      
      # Check for updates
      - name: 'Check for updates'
        run: |
          pushd ${{ github.workspace }}/workflows-ci
          env TREEDIR=${{ github.workspace }}/abbs NIGHTLY=${{ env.NIGHTLY }} ./check-update-job
          popd

      - name: 'Push the commits'
        run: |
          pushd ${{ github.workspace }}/abbs
          git push --force
